/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SalonsRouteImport } from './routes/salons'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SalonsSlugRouteImport } from './routes/salons.$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardServicesRouteImport } from './routes/dashboard.services'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardBarbersRouteImport } from './routes/dashboard.barbers'
import { Route as ApiPublicWhatsappRouteImport } from './routes/api/public/whatsapp'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SalonsRoute = SalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SalonsSlugRoute = SalonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SalonsRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServicesRoute = DashboardServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBarbersRoute = DashboardBarbersRouteImport.update({
  id: '/barbers',
  path: '/barbers',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicWhatsappRoute = ApiPublicWhatsappRouteImport.update({
  id: '/api/public/whatsapp',
  path: '/api/public/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/salons': typeof SalonsRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/barbers': typeof DashboardBarbersRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/salons/$slug': typeof SalonsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/salons': typeof SalonsRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/barbers': typeof DashboardBarbersRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/salons/$slug': typeof SalonsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/salons': typeof SalonsRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/barbers': typeof DashboardBarbersRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/services': typeof DashboardServicesRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/salons/$slug': typeof SalonsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/whatsapp': typeof ApiPublicWhatsappRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/salons'
    | '/signup'
    | '/dashboard/barbers'
    | '/dashboard/customers'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/salons/$slug'
    | '/dashboard/'
    | '/api/public/whatsapp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/salons'
    | '/signup'
    | '/dashboard/barbers'
    | '/dashboard/customers'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/salons/$slug'
    | '/dashboard'
    | '/api/public/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/salons'
    | '/signup'
    | '/dashboard/barbers'
    | '/dashboard/customers'
    | '/dashboard/services'
    | '/dashboard/settings'
    | '/salons/$slug'
    | '/dashboard/'
    | '/api/public/whatsapp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SalonsRoute: typeof SalonsRouteWithChildren
  SignupRoute: typeof SignupRoute
  ApiPublicWhatsappRoute: typeof ApiPublicWhatsappRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salons': {
      id: '/salons'
      path: '/salons'
      fullPath: '/salons'
      preLoaderRoute: typeof SalonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/salons/$slug': {
      id: '/salons/$slug'
      path: '/$slug'
      fullPath: '/salons/$slug'
      preLoaderRoute: typeof SalonsSlugRouteImport
      parentRoute: typeof SalonsRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/services': {
      id: '/dashboard/services'
      path: '/services'
      fullPath: '/dashboard/services'
      preLoaderRoute: typeof DashboardServicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/barbers': {
      id: '/dashboard/barbers'
      path: '/barbers'
      fullPath: '/dashboard/barbers'
      preLoaderRoute: typeof DashboardBarbersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/whatsapp': {
      id: '/api/public/whatsapp'
      path: '/api/public/whatsapp'
      fullPath: '/api/public/whatsapp'
      preLoaderRoute: typeof ApiPublicWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBarbersRoute: typeof DashboardBarbersRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardServicesRoute: typeof DashboardServicesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBarbersRoute: DashboardBarbersRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardServicesRoute: DashboardServicesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SalonsRouteChildren {
  SalonsSlugRoute: typeof SalonsSlugRoute
}

const SalonsRouteChildren: SalonsRouteChildren = {
  SalonsSlugRoute: SalonsSlugRoute,
}

const SalonsRouteWithChildren =
  SalonsRoute._addFileChildren(SalonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SalonsRoute: SalonsRouteWithChildren,
  SignupRoute: SignupRoute,
  ApiPublicWhatsappRoute: ApiPublicWhatsappRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
